apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mikbien/inz:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "61613"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_CONTACT_POINTS
              value: k8ssandra-dc1-stargate-service
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8ssandra-superuser
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8ssandra-superuser
                  key: password
            - name: CASSANDRA_DC
              value: "dc1"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8099
      targetPort: 8080
  type: NodePort