export const chatTypes = {
    DM_SEND: 'USER_SEND_MESSAGE',
    DM_RECEIVE: 'USER_RECEIVE_MESSAGE',

    DM_LOAD_REQUEST: 'DM_LOAD_REQUEST',
    DM_LOAD_ERROR: 'DM_LOAD_ERROR',
    DM_LOAD_SUCCESS: 'DM_LOAD_SUCCESS',

    DMS_REQUEST: 'DMS_REQUEST',
    DMS_REQUEST_FAIL: 'DMS_REQUEST_FAIL',
    DMS_REQUEST_SUCCESS: 'DMS_REQUEST_SUCCESS',

};
