export const meetingTypes = {
    MEETING_NEW_REQUEST: 'MEETING_NEW_REQUEST',
    MEETING_NEW_ERROR: 'MEETING_NEW_ERROR',
    MEETING_NEW_SUCCESS: 'MEETING_NEW_SUCCESS',

    MEETING_JOIN_REQUEST: 'MEETING_JOIN_REQUEST',
    MEETING_JOIN_ERROR: 'MEETING_JOIN_ERROR',
    MEETING_JOIN_SUCCESS: 'MEETING_JOIN_SUCCESS',

    MEETING_CANVAS_UPDATE: 'MEETING_CANVAS_UPDATE',

    MEETING_CHAT_SEND: 'MEETING_CHAT_SEND',
    MEETING_CHAT_RECEIVE: 'MEETING_CHAT_RECEIVE',
};
