export const userTypes = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_ERROR: 'USER_LOGIN_ERROR',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',

    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_ERROR: 'USER_REGISTER_ERROR',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',

    LOGOUT: 'USER_LOGOUT',
};
